### ISSUE TITLE
原因調査: DojoPaaS のサーバー生成スクリプトが動かない?

### ISSUE THREAD

**Issue by yasulab** [coderdojo-japan/dojopaas#125]
という現象を確認したので原因を調査します 🐛 👀 💨 
cc/ @sunabet @miya0001 

cf. [CoderDojo 西原を追加しました。 #124](https://github.com/coderdojo-japan/dojopaas/pull/124#issuecomment-493255145)

> 安川さま、
> 
> いつもお世話になっております。
> 
> サーバーが追加されません。
> https://github.com/coderdojo-japan/dojopaas/blob/gh-pages/instances.csv?fbclid=IwAR07OAty3C5GZhzlgLF2BSer7OaLvFOABcXn6xaopWyb0vJrSGnk2UYB2DU
> 申請に過不足・誤りがあるのでしょうか？
> ご教示ください。

**Comment by yasulab** [comment]
ログはこちら: https://travis-ci.org/coderdojo-japan/dojopaas/builds/531738097#L468-L517

> **Error: Error: 402: Payment Required**

なるほど...? 決済カードが必須になったから SAKURA Internet さん側で弾かれているっぽい....? 🤔💭
決済カードはそもそも登録していないはずなので、 @hourin さんにお伺いしてみます!

```bash
$ bash ./bin/deploy.sh
> dojopaas@1.0.0 deploy /home/travis/build/coderdojo-japan/dojopaas
> node dojopaas.js "--production"

Update startup scripts.
Archive ID:113100422585
Get a list of existing servers.
Create a server for coderdojo-nishihara.
/home/travis/build/coderdojo-japan/dojopaas/lib/Server.js:27
        if (err) throw new Error(err);
                 ^

Error: Error: 402: Payment Required
    at /home/travis/build/coderdojo-japan/dojopaas/lib/Server.js:27:24
    at _Request._onReadyStateChangeOnXHR (/home/travis/build/coderdojo-japan/dojopaas/node_modules/sacloud/lib/sacloud/client.request.js:126:4)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/travis/build/coderdojo-japan/dojopaas/node_modules/xhr2/lib/xhr2.js:64:9)
    at XMLHttpRequest._setReadyState (/home/travis/build/coderdojo-japan/dojopaas/node_modules/xhr2/lib/xhr2.js:360:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/travis/build/coderdojo-japan/dojopaas/node_modules/xhr2/lib/xhr2.js:478:12)
    at IncomingMessage.<anonymous> (/home/travis/build/coderdojo-japan/dojopaas/node_modules/xhr2/lib/xhr2.js:442:22)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)

npm ERR! Linux 4.4.0-101-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v7.10.1/bin/node" "/home/travis/.nvm/versions/node/v7.10.1/bin/npm" "run" "deploy" "--" "--production"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dojopaas@1.0.0 deploy: `node dojopaas.js "--production"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dojopaas@1.0.0 deploy script 'node dojopaas.js "--production"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dojopaas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dojopaas.js "--production"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dojopaas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dojopaas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/.npm/_logs/2019-05-13T11_40_13_152Z-debug.log

Done. Your build exited with 0.
```

**Comment by yasulab** [comment]
お問い合わせ Done ✅ ひとまずお返事待ち 😌 

![image](https://user-images.githubusercontent.com/155807/58023119-f4b76700-7b49-11e9-915f-eb833b2af222.png)

**Comment by yasulab** [comment]
こちら原因わかりました! 原因は次の通りで、先ほど対応していただきました ;)

https://github.com/coderdojo-japan/dojopaas/commit/6094f7d06c5e0db56f0e17d65c6c1b4e32ee42af のコミットで西原のサーバーが生成できると思うので、現在は CI 結果待ちです 👀 ✅ 

> 調査してもらった結果、会員ID(bmt47930)の基本情報(会社の住所など)が古かったので更新したところ、電話認証が必要になってしまっていたようです。認証を解除してもらいまして、サーバの作成と削除もできることを確認しました。お騒がせしてすみません。よろしくお願いします。

無事サーバーが生成できたら本 Issue を close しますね 😉

**Comment by yasulab** [comment]
> 無事サーバーが生成できたら

Successfully done! ✅ 
https://github.com/coderdojo-japan/dojopaas/commit/5e09d636ecfbcc5ae56aba3ffd5bf62040e52ee5#diff-3dfe38357946121c2f0b04a2f80cec54R43
